<?php

namespace App\DataFixtures;

use App\Entity\Country;
use App\Entity\Currency;
use App\Entity\Language;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Persistence\ObjectManager;

/**
 * @author Víctor <varroyo.a4b@gmail.com>
 */
class LoadCountryData implements FixtureInterface, OrderedFixtureInterface
{
    private $countries = [
        ['iso_code' => 'ad', 'name_canonical' => 'Andorra', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ae', 'name_canonical' => 'United Arab Emirates', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'af', 'name_canonical' => 'Afghanistan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ag', 'name_canonical' => 'Antigua and Barbuda', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ai', 'name_canonical' => 'Anguilla', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'al', 'name_canonical' => 'Albania', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'am', 'name_canonical' => 'Armenia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'an', 'name_canonical' => 'Netherlands Antilles', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ao', 'name_canonical' => 'Angola', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'aq', 'name_canonical' => 'Antarctica', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ar', 'name_canonical' => 'Argentina', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'as', 'name_canonical' => 'American Samoa', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'at', 'name_canonical' => 'Austria', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'au', 'name_canonical' => 'Australia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'aw', 'name_canonical' => 'Aruba', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ax', 'name_canonical' => 'Åland Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'az', 'name_canonical' => 'Azerbaijan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ba', 'name_canonical' => 'Bosnia and Herzegovina', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bb', 'name_canonical' => 'Barbados', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bd', 'name_canonical' => 'Bangladesh', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'be', 'name_canonical' => 'Belgium', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bf', 'name_canonical' => 'Burkina Faso', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bg', 'name_canonical' => 'Bulgaria', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bh', 'name_canonical' => 'Bahrain', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bi', 'name_canonical' => 'Burundi', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bj', 'name_canonical' => 'Benin', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bl', 'name_canonical' => 'Saint Barthelemy', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bm', 'name_canonical' => 'Bermuda', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bn', 'name_canonical' => 'Brunei', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bo', 'name_canonical' => 'Bolivia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'br', 'name_canonical' => 'Brazil', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bs', 'name_canonical' => 'Bahamas', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bt', 'name_canonical' => 'Bhutan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bv', 'name_canonical' => 'Bouvet Island', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bw', 'name_canonical' => 'Botswana', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'by', 'name_canonical' => 'Belarus', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'bz', 'name_canonical' => 'Belize', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ca', 'name_canonical' => 'Canada', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cc', 'name_canonical' => 'Cocos (Keeling) Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cd', 'name_canonical' => 'Congo, Dem. Republic', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cf', 'name_canonical' => 'Central African Republic', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cg', 'name_canonical' => 'Congo, Republic', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ch', 'name_canonical' => 'Switzerland', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ci', 'name_canonical' => 'Ivory Coast', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ck', 'name_canonical' => 'Cook Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cl', 'name_canonical' => 'Chile', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cm', 'name_canonical' => 'Cameroon', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cn', 'name_canonical' => 'China', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'co', 'name_canonical' => 'Colombia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cr', 'name_canonical' => 'Costa Rica', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cu', 'name_canonical' => 'Cuba', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cv', 'name_canonical' => 'Cape Verde', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cx', 'name_canonical' => 'Christmas Island', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cy', 'name_canonical' => 'Cyprus', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'cz', 'name_canonical' => 'Czech Republic', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'de', 'name_canonical' => 'Germany', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'dj', 'name_canonical' => 'Djibouti', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'dk', 'name_canonical' => 'Denmark', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'dm', 'name_canonical' => 'Dominica', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'do', 'name_canonical' => 'Dominican Republic', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'dz', 'name_canonical' => 'Algeria', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ec', 'name_canonical' => 'Ecuador', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ee', 'name_canonical' => 'Estonia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'eg', 'name_canonical' => 'Egypt', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'eh', 'name_canonical' => 'Western Sahara', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'er', 'name_canonical' => 'Eritrea', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'es', 'name_canonical' => 'Spain', 'currency_id' => 1, 'language_id' => 2, 'active' => 0, ],
        ['iso_code' => 'et', 'name_canonical' => 'Ethiopia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'fi', 'name_canonical' => 'Finland', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'fj', 'name_canonical' => 'Fiji', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'fk', 'name_canonical' => 'Falkland Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'fm', 'name_canonical' => 'Micronesia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'fo', 'name_canonical' => 'Faroe Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'fr', 'name_canonical' => 'France', 'currency_id' => 1, 'language_id' => 3, 'active' => 0, ],
        ['iso_code' => 'ga', 'name_canonical' => 'Gabon', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gb', 'name_canonical' => 'United Kingdom', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gd', 'name_canonical' => 'Grenada', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ge', 'name_canonical' => 'Georgia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gf', 'name_canonical' => 'French Guiana', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gg', 'name_canonical' => 'Guernsey', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gh', 'name_canonical' => 'Ghana', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gi', 'name_canonical' => 'Gibraltar', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gl', 'name_canonical' => 'Greenland', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gm', 'name_canonical' => 'Gambia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gn', 'name_canonical' => 'Guinea', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gp', 'name_canonical' => 'Guadeloupe', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gq', 'name_canonical' => 'Equatorial Guinea', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gr', 'name_canonical' => 'Greece', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gs', 'name_canonical' => 'South Georgia and the South Sandwich Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gt', 'name_canonical' => 'Guatemala', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gu', 'name_canonical' => 'Guam', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gw', 'name_canonical' => 'Guinea-Bissau', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'gy', 'name_canonical' => 'Guyana', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'hk', 'name_canonical' => 'HongKong', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'hm', 'name_canonical' => 'Heard Island and McDonald Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'hn', 'name_canonical' => 'Honduras', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'hr', 'name_canonical' => 'Croatia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ht', 'name_canonical' => 'Haiti', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'hu', 'name_canonical' => 'Hungary', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'id', 'name_canonical' => 'Indonesia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ie', 'name_canonical' => 'Ireland', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'il', 'name_canonical' => 'Israel', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'im', 'name_canonical' => 'Man Island', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'in', 'name_canonical' => 'India', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'io', 'name_canonical' => 'British Indian Ocean Territory', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'iq', 'name_canonical' => 'Iraq', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ir', 'name_canonical' => 'Iran', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'is', 'name_canonical' => 'Iceland', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'it', 'name_canonical' => 'Italy', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'je', 'name_canonical' => 'Jersey', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'jm', 'name_canonical' => 'Jamaica', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'jo', 'name_canonical' => 'Jordan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'jp', 'name_canonical' => 'Japan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ke', 'name_canonical' => 'Kenya', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'kg', 'name_canonical' => 'Kyrgyzstan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'kh', 'name_canonical' => 'Cambodia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ki', 'name_canonical' => 'Kiribati', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'km', 'name_canonical' => 'Comoros', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'kn', 'name_canonical' => 'Saint Kitts and Nevis', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'kp', 'name_canonical' => 'Korea, Dem. Republic of', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'kr', 'name_canonical' => 'South Korea', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'kw', 'name_canonical' => 'Kuwait', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ky', 'name_canonical' => 'Cayman Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'kz', 'name_canonical' => 'Kazakhstan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'la', 'name_canonical' => 'Laos', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'lb', 'name_canonical' => 'Lebanon', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'lc', 'name_canonical' => 'Saint Lucia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'li', 'name_canonical' => 'Liechtenstein', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'lk', 'name_canonical' => 'Sri Lanka', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'lr', 'name_canonical' => 'Liberia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ls', 'name_canonical' => 'Lesotho', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'lt', 'name_canonical' => 'Lithuania', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'lu', 'name_canonical' => 'Luxemburg', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'lv', 'name_canonical' => 'Latvia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ly', 'name_canonical' => 'Libya', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ma', 'name_canonical' => 'Morocco', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mc', 'name_canonical' => 'Monaco', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'md', 'name_canonical' => 'Moldova', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'me', 'name_canonical' => 'Montenegro', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mf', 'name_canonical' => 'Saint Martin', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mg', 'name_canonical' => 'Madagascar', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mh', 'name_canonical' => 'Marshall Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mk', 'name_canonical' => 'Macedonia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ml', 'name_canonical' => 'Mali', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mm', 'name_canonical' => 'Burma (Myanmar)', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mn', 'name_canonical' => 'Mongolia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mo', 'name_canonical' => 'Macau', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mp', 'name_canonical' => 'Northern Mariana Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mq', 'name_canonical' => 'Martinique', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mr', 'name_canonical' => 'Mauritania', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ms', 'name_canonical' => 'Montserrat', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mt', 'name_canonical' => 'Malta', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mu', 'name_canonical' => 'Mauritius', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mv', 'name_canonical' => 'Maldives', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mw', 'name_canonical' => 'Malawi', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mx', 'name_canonical' => 'Mexico', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'my', 'name_canonical' => 'Malaysia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'mz', 'name_canonical' => 'Mozambique', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'na', 'name_canonical' => 'Namibia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'nc', 'name_canonical' => 'New Caledonia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ne', 'name_canonical' => 'Niger', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'nf', 'name_canonical' => 'Norfolk Island', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ng', 'name_canonical' => 'Nigeria', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ni', 'name_canonical' => 'Nicaragua', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'nl', 'name_canonical' => 'Netherlands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'no', 'name_canonical' => 'Norway', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'np', 'name_canonical' => 'Nepal', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'nr', 'name_canonical' => 'Nauru', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'nu', 'name_canonical' => 'Niue', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'nz', 'name_canonical' => 'New Zealand', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'om', 'name_canonical' => 'Oman', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pa', 'name_canonical' => 'Panama', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pe', 'name_canonical' => 'Peru', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pf', 'name_canonical' => 'French Polynesia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pg', 'name_canonical' => 'Papua New Guinea', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ph', 'name_canonical' => 'Philippines', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pk', 'name_canonical' => 'Pakistan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pl', 'name_canonical' => 'Poland', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pm', 'name_canonical' => 'Saint Pierre and Miquelon', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pn', 'name_canonical' => 'Pitcairn', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pr', 'name_canonical' => 'Puerto Rico', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ps', 'name_canonical' => 'Palestinian Territories', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pt', 'name_canonical' => 'Portugal', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'pw', 'name_canonical' => 'Palau', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'py', 'name_canonical' => 'Paraguay', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'qa', 'name_canonical' => 'Qatar', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 're', 'name_canonical' => 'Reunion Island', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ro', 'name_canonical' => 'Romania', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'rs', 'name_canonical' => 'Serbia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ru', 'name_canonical' => 'Russian Federation', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'rw', 'name_canonical' => 'Rwanda', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sa', 'name_canonical' => 'Saudi Arabia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sb', 'name_canonical' => 'Solomon Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sc', 'name_canonical' => 'Seychelles', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sd', 'name_canonical' => 'Sudan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'se', 'name_canonical' => 'Sweden', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sg', 'name_canonical' => 'Singapore', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'si', 'name_canonical' => 'Slovenia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sj', 'name_canonical' => 'Svalbard and Jan Mayen', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sk', 'name_canonical' => 'Slovakia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sl', 'name_canonical' => 'Sierra Leone', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sm', 'name_canonical' => 'San Marino', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sn', 'name_canonical' => 'Senegal', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'so', 'name_canonical' => 'Somalia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sr', 'name_canonical' => 'Suriname', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'st', 'name_canonical' => 'São Tomé and Príncipe', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sv', 'name_canonical' => 'El Salvador', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sy', 'name_canonical' => 'Syria', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'sz', 'name_canonical' => 'Swaziland', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tc', 'name_canonical' => 'Turks and Caicos Islands', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'td', 'name_canonical' => 'Chad', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tf', 'name_canonical' => 'French Southern Territories', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tg', 'name_canonical' => 'Togo', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'th', 'name_canonical' => 'Thailand', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tj', 'name_canonical' => 'Tajikistan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tk', 'name_canonical' => 'Tokelau', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tl', 'name_canonical' => 'East Timor', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tm', 'name_canonical' => 'Turkmenistan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tn', 'name_canonical' => 'Tunisia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'to', 'name_canonical' => 'Tonga', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tr', 'name_canonical' => 'Turkey', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tt', 'name_canonical' => 'Trinidad and Tobago', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tv', 'name_canonical' => 'Tuvalu', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tw', 'name_canonical' => 'Taiwan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'tz', 'name_canonical' => 'Tanzania', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ua', 'name_canonical' => 'Ukraine', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ug', 'name_canonical' => 'Uganda', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'us', 'name_canonical' => 'United States', 'currency_id' => 2, 'language_id' => 1, 'active' => 0, ],
        ['iso_code' => 'uy', 'name_canonical' => 'Uruguay', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'uz', 'name_canonical' => 'Uzbekistan', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'va', 'name_canonical' => 'Vatican City State', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'vc', 'name_canonical' => 'Saint Vincent and the Grenadines', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 've', 'name_canonical' => 'Venezuela', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'vg', 'name_canonical' => 'Virgin Islands (British)', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'vi', 'name_canonical' => 'Virgin Islands (U.S.)', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'vn', 'name_canonical' => 'Vietnam', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'vu', 'name_canonical' => 'Vanuatu', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'wf', 'name_canonical' => 'Wallis and Futuna', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ws', 'name_canonical' => 'Samoa', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'ye', 'name_canonical' => 'Yemen', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'yt', 'name_canonical' => 'Mayotte', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'za', 'name_canonical' => 'South Africa', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'zm', 'name_canonical' => 'Zambia', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
        ['iso_code' => 'zw', 'name_canonical' => 'Zimbabwe', 'currency_id' => null, 'language_id' => null, 'active' => 0, ],
    ];

    public function load(ObjectManager $manager)
    {
        $countryManager = $manager->getRepository(Country::class);
        $currencyManager = $manager->getRepository(Currency::class);
        $languageManager = $manager->getRepository(Language::class);

        foreach ($this->countries as $countryData) {
            $country = $countryManager->findOneBy(['isoCode' => $countryData['iso_code']]);

            if ($country) {
                continue;
            }

            $country = new Country();
            $country->setIsoCode($countryData['iso_code']);
            $country->setNameCanonical($countryData['name_canonical']);

            $currency = $currencyManager->findOneById($countryData['currency_id']);
            if ($currency) {
                $country->setCurrency($currency);
            }

            $language = $languageManager->findOneById($countryData['language_id']);
            if ($language) {
                $country->setLanguage($language);
            }
            $country->setActive($countryData['active']);

            $manager->persist($country);
        }

        $manager->flush();
    }

    public function getOrder()
    {
        return 3;
    }
}
